### ISSUE TITLE
MAC OS 13.6.1 (22G313) python报错

### ISSUE THREAD

**Issue by swiftPeter** [SwaggyMacro/BarrageGPT#2]
2023-11-26 20:11:56.660 python[21859:1142294] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007ff80290811a __exceptionPreprocess + 242
        1   libobjc.A.dylib                     0x00007ff80242e0b7 objc_exception_throw + 48
        2   CoreFoundation                      0x00007ff802930296 -[NSException raise] + 9
        3   AppKit                              0x00007ff805951e7e -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 307
        4   AppKit                              0x00007ff80593e394 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1227
        5   AppKit                              0x00007ff80593dec2 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
        6   AppKit                              0x00007ff805c08ec3 -[NSWindow initWithContentRect:styleMask:backing:defer:screen:] + 50
        7   libqcocoa.dylib                     0x000000010e456312 qt_plugin_instance + 196690
        8   libqcocoa.dylib                     0x000000010e441c88 qt_plugin_instance + 113096
        9   libqcocoa.dylib                     0x000000010e43abd2 qt_plugin_instance + 84242
        10  libqcocoa.dylib                     0x000000010e43a646 qt_plugin_instance + 82822
        11  QtGui                               0x000000010b9a77f2 _ZN14QWindowPrivate6createEby + 146
        12  QtWidgets                           0x000000010adfbd36 _ZN14QWidgetPrivate6createEv + 1206
        13  QtWidgets                           0x000000010adfaa51 _ZN7QWidget6createEybb + 321
        14  QtWidgets                           0x000000010af4fac8 _ZN8QMenuBar7hoveredEP7QAction + 1032
        15  QtWidgets                           0x000000010af4f7a5 _ZN8QMenuBar7hoveredEP7QAction + 229
        16  QtWidgets.abi3.so                   0x000000010a32d414 _ZL18init_type_QMenuBarP17_sipSimpleWrapperP7_objectS2_PS2_S3_S3_ + 116
        17  sip.cpython-39-darwin.so            0x00000001097a390f sipSimpleWrapper_init + 495
        18  Python3                             0x000000010918bfe4 _PyType_Lookup + 1940
        19  Python3                             0x0000000109134dc0 _PyObject_MakeTpCall + 384
        20  Python3                             0x00000001092119d0 _PyEval_EvalFrameDefault + 36720
        21  Python3                             0x000000010920e454 _PyEval_EvalFrameDefault + 23028
        22  Python3                             0x00000001091355e0 _PyFunction_Vectorcall + 512
        23  Python3                             0x000000010913790f PyMethod_New + 367
        24  Python3                             0x00000001092118fb _PyEval_EvalFrameDefault + 36507
        25  Python3                             0x000000010920e454 _PyEval_EvalFrameDefault + 23028
        26  Python3                             0x00000001091355e0 _PyFunction_Vectorcall + 512
        27  Python3                             0x000000010920e8c7 _PyEval_EvalFrameDefault + 24167
        28  Python3                             0x00000001091355e0 _PyFunction_Vectorcall + 512
        29  Python3                             0x00000001092118fb _PyEval_EvalFrameDefault + 36507
        30  Python3                             0x000000010920e436 _PyEval_EvalFrameDefault + 22998
        31  Python3                             0x00000001091355e0 _PyFunction_Vectorcall + 512
        32  Python3                             0x00000001092118fb _PyEval_EvalFrameDefault + 36507
        33  Python3                             0x000000010920e436 _PyEval_EvalFrameDefault + 22998
        34  Python3                             0x00000001091355e0 _PyFunction_Vectorcall + 512
        35  Python3                             0x0000000109137998 PyMethod_New + 504
        36  Python3                             0x00000001092a9656 PyInit__thread + 5702
        37  Python3                             0x000000010925c269 PyThread_start_new_thread + 313
        38  libsystem_pthread.dylib             0x00007ff8027b51d3 _pthread_start + 125
        39  libsystem_pthread.dylib             0x00007ff8027b0bd3 thread_start + 15
)
libc++abi: terminating due to uncaught exception of type NSException
Abort trap: 6

**Comment by SwaggyMacro** [comment]
查了一下看起来像是macos的python问题，手上没有mac，没办法解决🤔
