### ISSUE TITLE
answer无法换行

### ISSUE THREAD

**Issue by chuanSir123** [SwaggyMacro/BarrageGPT#4]
MAIN_WINDOW.update_answer_signal.emit("第一行\n第二行")
字符串无论是\n还是\r\n还是<br>都无法换行…请问下怎么可以实现换行

**Comment by SwaggyMacro** [comment]
因为这个textEdit控件是设置成Markdown格式了，Markdown的换行逻辑是两个空格加换行符，所以你需要emit("第一行  \n第二行")
